/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/digital-armory` | `/digital-armory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/privacy` | `/privacy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/redeem_dashboard` | `/redeem_dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/terms` | `/terms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pay` | `/pay`; params?: Router.UnknownInputParams; } | { pathname: `/auth/ForgotPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/ResetPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/digital-armory` | `/digital-armory`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/privacy` | `/privacy`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/redeem_dashboard` | `/redeem_dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/terms` | `/terms`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pay` | `/pay`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/ForgotPasswordScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/ResetPasswordScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/digital-armory${`?${string}` | `#${string}` | ''}` | `/digital-armory${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/privacy${`?${string}` | `#${string}` | ''}` | `/privacy${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/redeem_dashboard${`?${string}` | `#${string}` | ''}` | `/redeem_dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/terms${`?${string}` | `#${string}` | ''}` | `/terms${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pay${`?${string}` | `#${string}` | ''}` | `/pay${`?${string}` | `#${string}` | ''}` | `/auth/ForgotPasswordScreen${`?${string}` | `#${string}` | ''}` | `/auth/ResetPasswordScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/digital-armory` | `/digital-armory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/privacy` | `/privacy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/redeem_dashboard` | `/redeem_dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/terms` | `/terms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pay` | `/pay`; params?: Router.UnknownInputParams; } | { pathname: `/auth/ForgotPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `/auth/ResetPasswordScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
