# fly.toml app configuration file generated for team556-solana-api on 2025-04-26T17:58:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'team556-solana-api'
primary_region = 'lax'
console_command = '/bin/sh'

[build]
  # dockerfile = 'apps/solana-api/Dockerfile'
  dockerfile = "Dockerfile" # Path relative to this fly.toml file

[http_service]
  internal_port = 6000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
